server:
  port: 8080

spring:
  application:
    name: apiGateway
  config:
    import: consul:${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}

  cloud:
    consul:
      discovery:
        #preferIpAddress: true
        instanceId: ${spring.application.name}:${random.value}
        deregister: true

#servers:
#  - url: https://localhost:8081/v3/api-docs
#    description: Production server (uses live data)
#con esta configuracion en gateway se añaden todos los servicios y utiliza consul para traducir las ip's
    #en local falla pq se registran con ip's del tipo 10.144.0.2:8081... no se muy bien pq
    #meter esto en consul
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#      routes:
#        - id: example-service
#          uri: lb://example-service
#          predicates:
#            - Path=/entity/**
#          filters:
#            - RewritePath=/entity/(?<path>.*), /$\{path}
#        - id: openapi
#          uri: http://localhost:${server.port}
#          predicates:
#           - Path=/v3/api-docs/**
#          filters:
#           - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs